version: '3'
services:
    scraper-de:
        image: docker.crosslang.com/cefat4cities/scraper
        volumes:
            - "scraped-data-de:/output"
        labels:
            kompose.image-pull-secret: "docker.crosslang.com"
            kompose.volume.size: 50Gi
        environment:
            - language=de
        network_mode: "bridge"

    scraper-fr:
        image: docker.crosslang.com/cefat4cities/scraper
        volumes:
            - "scraped-data-fr:/output"
        labels:
            kompose.image-pull-secret: "docker.crosslang.com"
            kompose.volume.size: 50Gi
        environment:
            - language=fr
        network_mode: "bridge"

    scraper-hr:
        image: docker.crosslang.com/cefat4cities/scraper
        volumes:
            - "scraped-data-hr:/output"
        labels:
            kompose.image-pull-secret: "docker.crosslang.com"
            kompose.volume.size: 50Gi
        environment:
            - language=hr
        network_mode: "bridge"

    scraper-it:
        image: docker.crosslang.com/cefat4cities/scraper
        volumes:
            - "scraped-data-it:/output"
        labels:
            kompose.image-pull-secret: "docker.crosslang.com"
            kompose.volume.size: 50Gi
        environment:
            - language=it
        network_mode: "bridge"

    scraper-no:
        image: docker.crosslang.com/cefat4cities/scraper
        volumes:
            - "scraped-data-no:/output"
        labels:
            kompose.image-pull-secret: "docker.crosslang.com"
            kompose.volume.size: 50Gi
        environment:
            - language=no
        network_mode: "bridge"

    scraper-sl:
        image: docker.crosslang.com/cefat4cities/scraper
        volumes:
            - "scraped-data-sl:/output"
        labels:
            kompose.image-pull-secret: "docker.crosslang.com"
            kompose.volume.size: 50Gi
        environment:
            - language=sl
        network_mode: "bridge"