apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.image-pull-secret: crosslang
    kompose.version: 1.19.0 (f63a961c)
    kompose.volume.size: 50Gi
  creationTimestamp: null
  labels:
    io.kompose.service: scraper-fr
  name: scraper-fr
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: scraper-fr
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.image-pull-secret: crosslang
        kompose.version: 1.19.0 (f63a961c)
        kompose.volume.size: 50Gi
      creationTimestamp: null
      labels:
        io.kompose.service: scraper-fr
    spec:
      containers:
      - env:
        - name: language
          value: fr
        image: docker.crosslang.com/cefat4cities/scraper
        name: scraper-fr
        resources: {}
        volumeMounts:
        - mountPath: /output
          name: scraped-data-fr
      imagePullSecrets:
      - name: crosslang
      restartPolicy: Always
      volumes:
      - name: scraped-data-fr
        persistentVolumeClaim:
          claimName: scraped-data-fr
status: {}
